os:
  - linux
before_install:
  - sudo apt-get -y install libsdl2-dev libsdl2-ttf-dev
language: perl6
perl6:
  - latest
install:
  - rakudobrew build zef
  - zef install --deps-only SDL2::Raw
  - zef install --deps-only --/test .
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -vr --ext .t --ext .t6 --ext .rakutest t

